CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE usuario_permisos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    usuario_id integer NOT NULL,
    permiso_id integer NOT NULL,
    activo boolean NOT NULL,
    fecha_asignacion timestamp with time zone NOT NULL,
    CONSTRAINT "PK_usuario_permisos" PRIMARY KEY (id),
    CONSTRAINT "FK_usuario_permisos_permisos_permiso_id" FOREIGN KEY (permiso_id) REFERENCES permisos (id) ON DELETE CASCADE,
    CONSTRAINT "FK_usuario_permisos_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE INDEX "IX_usuario_permisos_permiso_id" ON usuario_permisos (permiso_id);

CREATE INDEX "IX_usuario_permisos_usuario_id" ON usuario_permisos (usuario_id);

CREATE UNIQUE INDEX "IX_usuario_permisos_usuario_id_permiso_id" ON usuario_permisos (usuario_id, permiso_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260116135743_InitialBaseline', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE movimientos ADD fecha_limite_devolucion timestamp without time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216204122_AddFechaLimiteDevolucion', '8.0.0');

COMMIT;

