@echo off
echo Cerrando backend si esta en ejecucion...
taskkill /IM SistemaGestionDocumental.exe /F >nul 2>&1
timeout /t 2 /nobreak >nul
echo Limpiando proyecto...
dotnet clean
echo Iniciando backend...
dotnet run
