// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaGestionDocumental.Data;

#nullable disable

namespace SistemaGestionDocumental.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216204122_AddFechaLimiteDevolucion")]
    partial class AddFechaLimiteDevolucion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionDocumental.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("documento_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_lectura");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<int?>("MovimientoId")
                        .HasColumnType("integer")
                        .HasColumnName("movimiento_id");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_alerta");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("Leida");

                    b.HasIndex("MovimientoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("alertas");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("documento_id");

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("extension");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<int?>("Tamano")
                        .HasColumnType("integer")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_contenido");

                    b.Property<string>("UrlArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_archivo");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("anexos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_accion");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("integer")
                        .HasColumnName("registro_id");

                    b.Property<string>("TablaAfectada")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tabla_afectada");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("FechaAccion");

                    b.HasIndex("TablaAfectada");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Carpeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int?>("CarpetaPadreId")
                        .HasColumnType("integer")
                        .HasColumnName("carpeta_padre_id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Gestion")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("gestion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("RangoFin")
                        .HasColumnType("integer")
                        .HasColumnName("rango_fin");

                    b.Property<int?>("RangoInicio")
                        .HasColumnType("integer")
                        .HasColumnName("rango_inicio");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_creacion_id");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("CarpetaPadreId");

                    b.HasIndex("Gestion");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("Nombre", "Gestion", "CarpetaPadreId");

                    b.ToTable("carpetas");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("actualizado_por");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean")
                        .HasColumnName("editable");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_dato");

                    b.Property<string>("Valor")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ActualizadoPor");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuracion");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("AreaActualId")
                        .HasColumnType("integer")
                        .HasColumnName("area_actual_id");

                    b.Property<int>("AreaOrigenId")
                        .HasColumnType("integer")
                        .HasColumnName("area_origen_id");

                    b.Property<int?>("CarpetaId")
                        .HasColumnType("integer")
                        .HasColumnName("carpeta_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoQR")
                        .HasColumnType("text")
                        .HasColumnName("codigo_qr");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_documento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("Gestion")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("gestion");

                    b.Property<string>("IdDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_documento");

                    b.Property<int>("NivelConfidencialidad")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_confidencialidad");

                    b.Property<string>("NumeroCorrelativo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_correlativo");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer")
                        .HasColumnName("responsable_id");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_documento_id");

                    b.Property<string>("UbicacionFisica")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ubicacion_fisica");

                    b.Property<string>("UrlQR")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_qr");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AreaActualId");

                    b.HasIndex("AreaOrigenId");

                    b.HasIndex("CarpetaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaDocumento");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("Gestion", "NumeroCorrelativo");

                    b.ToTable("documentos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.DocumentoPalabraClave", b =>
                {
                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("documento_id");

                    b.Property<int>("PalabraClaveId")
                        .HasColumnType("integer")
                        .HasColumnName("palabra_clave_id");

                    b.HasKey("DocumentoId", "PalabraClaveId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("PalabraClaveId");

                    b.ToTable("documento_palabras_clave");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.HistorialDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaAnteriorId")
                        .HasColumnType("integer")
                        .HasColumnName("area_anterior_id");

                    b.Property<int?>("AreaNuevaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_nueva_id");

                    b.Property<string>("CampoModificado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("campo_modificado");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("documento_id");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .HasColumnType("text")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<string>("TipoCambio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_cambio");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("AreaAnteriorId");

                    b.HasIndex("AreaNuevaId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_documento");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaDestinoId")
                        .HasColumnType("integer")
                        .HasColumnName("area_destino_id");

                    b.Property<int?>("AreaOrigenId")
                        .HasColumnType("integer")
                        .HasColumnName("area_origen_id");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("documento_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_devolucion");

                    b.Property<DateTime?>("FechaLimiteDevolucion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_limite_devolucion");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_movimiento");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("AreaDestinoId");

                    b.HasIndex("AreaOrigenId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("FechaMovimiento");

                    b.HasIndex("UsuarioId");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.PalabraClave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Palabra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("palabra");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Palabra")
                        .IsUnique();

                    b.ToTable("palabras_clave");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modulo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Modulo");

                    b.ToTable("permisos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer")
                        .HasColumnName("permiso_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("Rol");

                    b.HasIndex("Rol", "PermisoId")
                        .IsUnique();

                    b.ToTable("rol_permisos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipos_documento");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PreguntaSecretaId")
                        .HasColumnType("integer")
                        .HasColumnName("pregunta_secreta_id");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reset_token_expiry");

                    b.Property<string>("RespuestaSecretaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("respuesta_secreta_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<bool>("SolicitudRechazada")
                        .HasColumnType("boolean")
                        .HasColumnName("solicitud_rechazada");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("AreaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.UsuarioPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("Denegado")
                        .HasColumnType("boolean")
                        .HasColumnName("denegado");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer")
                        .HasColumnName("permiso_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "PermisoId")
                        .IsUnique();

                    b.ToTable("usuario_permisos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Alerta", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Documento", "Documento")
                        .WithMany("Alertas")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaGestionDocumental.Models.Movimiento", "Movimiento")
                        .WithMany()
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Documento");

                    b.Navigation("Movimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Anexo", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Documento", "Documento")
                        .WithMany("Anexos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Auditoria", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Carpeta", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Carpeta", "CarpetaPadre")
                        .WithMany("Subcarpetas")
                        .HasForeignKey("CarpetaPadreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CarpetaPadre");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Configuracion", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "ActualizadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ActualizadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActualizadoPorUsuario");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Documento", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Area", "AreaActual")
                        .WithMany()
                        .HasForeignKey("AreaActualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionDocumental.Models.Area", "AreaOrigen")
                        .WithMany("DocumentosOrigen")
                        .HasForeignKey("AreaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionDocumental.Models.Carpeta", "Carpeta")
                        .WithMany("Documentos")
                        .HasForeignKey("CarpetaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "Responsable")
                        .WithMany("DocumentosResponsable")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaGestionDocumental.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaActual");

                    b.Navigation("AreaOrigen");

                    b.Navigation("Carpeta");

                    b.Navigation("Responsable");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.DocumentoPalabraClave", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Documento", "Documento")
                        .WithMany("DocumentoPalabrasClaves")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionDocumental.Models.PalabraClave", "PalabraClave")
                        .WithMany("DocumentoPalabrasClaves")
                        .HasForeignKey("PalabraClaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("PalabraClave");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.HistorialDocumento", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Area", "AreaAnterior")
                        .WithMany()
                        .HasForeignKey("AreaAnteriorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SistemaGestionDocumental.Models.Area", "AreaNueva")
                        .WithMany()
                        .HasForeignKey("AreaNuevaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SistemaGestionDocumental.Models.Documento", "Documento")
                        .WithMany("HistorialDocumentos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AreaAnterior");

                    b.Navigation("AreaNueva");

                    b.Navigation("Documento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Movimiento", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Area", "AreaDestino")
                        .WithMany("MovimientosDestino")
                        .HasForeignKey("AreaDestinoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaGestionDocumental.Models.Area", "AreaOrigen")
                        .WithMany("MovimientosOrigen")
                        .HasForeignKey("AreaOrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaGestionDocumental.Models.Documento", "Documento")
                        .WithMany("Movimientos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AreaDestino");

                    b.Navigation("AreaOrigen");

                    b.Navigation("Documento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.RolPermiso", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Usuario", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.UsuarioPermiso", b =>
                {
                    b.HasOne("SistemaGestionDocumental.Models.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionDocumental.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Area", b =>
                {
                    b.Navigation("DocumentosOrigen");

                    b.Navigation("MovimientosDestino");

                    b.Navigation("MovimientosOrigen");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Carpeta", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Subcarpetas");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Documento", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Anexos");

                    b.Navigation("DocumentoPalabrasClaves");

                    b.Navigation("HistorialDocumentos");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.PalabraClave", b =>
                {
                    b.Navigation("DocumentoPalabrasClaves");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("SistemaGestionDocumental.Models.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("DocumentosResponsable");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
