import 'package:flutter/material.dart';
import '../constants.dart';

class DocUploadCard extends StatelessWidget {
  final String title;
  final String description;
  final String? path;
  final bool isLoading;
  final bool isRequired;
  final bool enabled;
  final bool isAutoGenerated;
  final bool canGenerate;
  final VoidCallback? onUpload;
  final VoidCallback? onPreview;
  final VoidCallback? onDelete;
  final IconData? customIcon;

  const DocUploadCard({
    super.key,
    required this.title,
    required this.description,
    this.path,
    this.isLoading = false,
    this.isRequired = false,
    this.enabled = true,
    this.isAutoGenerated = false,
    this.canGenerate = false,
    this.onUpload,
    this.onPreview,
    this.onDelete,
    this.customIcon,
  });

  @override
  Widget build(BuildContext context) {
    final hasDoc = path != null && path!.isNotEmpty;
    // Removed direct reference to MisDocumentosConstants to make it self-contained if needed, 
    // but using them for consistency with the app's look.

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Theme.of(context).cardColor,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: hasDoc 
            ? MisDocumentosConstants.kSuccessColor.withOpacity(0.3) 
            : Colors.grey.shade200,
          width: 1,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(16),
        child: Stack(
          children: [
            Positioned(
              left: 0,
              top: 0,
              bottom: 0,
              child: Container(
                width: 4,
                color: hasDoc ? MisDocumentosConstants.kSuccessColor : Colors.transparent,
              ),
            ),
            Material(
              color: Colors.transparent,
              child: InkWell(
                onTap: hasDoc ? onPreview : (enabled ? onUpload : null),
                child: Padding(
                  padding: const EdgeInsets.all(14),
                  child: Row(
                    children: [
                      Container(
                        width: 48,
                        height: 48,
                        decoration: BoxDecoration(
                          color: hasDoc ? MisDocumentosConstants.kSuccessColor.withOpacity(0.1) : Colors.grey.shade50,
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: isLoading
                            ? const Center(child: SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2.5)))
                            : Icon(
                                hasDoc 
                                    ? Icons.check_circle_rounded 
                                    : (customIcon ?? (canGenerate ? Icons.auto_awesome_rounded : Icons.cloud_upload_outlined)),
                                color: hasDoc 
                                    ? MisDocumentosConstants.kSuccessColor 
                                    : (canGenerate ? MisDocumentosConstants.kPrimaryColor : Colors.grey.shade500),
                                size: 26,
                              ),
                      ),
                      const SizedBox(width: 14),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Expanded(
                                  child: Text(
                                    title,
                                    style: const TextStyle(
                                      fontFamily: MisDocumentosConstants.fontHeading,
                                      fontWeight: FontWeight.w700,
                                      fontSize: 14,
                                      color: MisDocumentosConstants.kTextColor,
                                    ),
                                    maxLines: 1,
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ),
                                if (isRequired && !hasDoc)
                                  Container(
                                    padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                    decoration: BoxDecoration(
                                      color: MisDocumentosConstants.kErrorColor.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(4),
                                    ),
                                    child: const Text(
                                      'REQ',
                                      style: TextStyle(color: MisDocumentosConstants.kErrorColor, fontSize: 8, fontWeight: FontWeight.w800),
                                    ),
                                  ),
                              ],
                            ),
                            const SizedBox(height: 2),
                            Text(
                              hasDoc ? 'Documento cargado correctamente' : description,
                              style: TextStyle(
                                fontFamily: MisDocumentosConstants.fontBody,
                                fontSize: 12,
                                color: hasDoc 
                                    ? MisDocumentosConstants.kSuccessColor.withOpacity(0.8)
                                    : MisDocumentosConstants.kTextSecondary,
                                fontWeight: hasDoc ? FontWeight.w500 : FontWeight.normal,
                              ),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 8),
                      if (hasDoc)
                        Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                              decoration: BoxDecoration(
                                color: MisDocumentosConstants.kSuccessColor.withOpacity(0.1),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: const Text(
                                'Ver',
                                style: TextStyle(
                                  color: MisDocumentosConstants.kSuccessColor,
                                  fontSize: 12,
                                  fontWeight: FontWeight.w700,
                                ),
                              ),
                            ),
                            PopupMenuButton<String>(
                              icon: const Icon(Icons.more_vert_rounded, color: Colors.grey, size: 20),
                              padding: EdgeInsets.zero,
                              onSelected: (val) {
                                if (val == 'preview') onPreview?.call();
                                if (val == 'delete') onDelete?.call();
                              },
                              itemBuilder: (ctx) => [
                                const PopupMenuItem(value: 'preview', child: Text('Ver Documento')),
                                const PopupMenuItem(value: 'delete', child: Text('Eliminar', style: TextStyle(color: Colors.red))),
                              ],
                            ),
                          ],
                        )
                      else if (!isLoading)
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                          decoration: BoxDecoration(
                            color: canGenerate
                                ? MisDocumentosConstants.kPrimaryColor.withOpacity(0.1)
                                : Colors.grey.shade100,
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(
                              color: canGenerate
                                  ? MisDocumentosConstants.kPrimaryColor.withOpacity(0.3)
                                  : Colors.grey.shade300,
                            )
                          ),
                          child: Text(
                            canGenerate ? 'Generar' : 'Subir',
                            style: TextStyle(
                              color: canGenerate
                                  ? MisDocumentosConstants.kPrimaryColor
                                  : Colors.grey.shade700,
                              fontSize: 12,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

